# Artificial Neural Network

### Importing the libraries

In [0]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [144]:
tf.__version__

'2.2.0'

## Part 1 - Data Preprocessing

### Importing the dataset

In [0]:
dataset = pd.read_csv('Churn_Modelling.csv')
X = dataset.iloc[:, 3:-1].values
y = dataset.iloc[:, -1].values

In [146]:
print(X[0])

[619 'France' 'Female' 42 2 0.0 1 1 1 101348.88]


In [147]:
print(y)

[1 0 1 ... 1 1 0]


### Encoding categorical data

Label Encoding the "Gender" column

In [0]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:, 2] = le.fit_transform(X[:, 2])

In [149]:
print(X[0:2])

[[619 'France' 0 42 2 0.0 1 1 1 101348.88]
 [608 'Spain' 0 41 1 83807.86 1 0 1 112542.58]]


One Hot Encoding the "Geography" column

In [0]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [151]:
print(X[0:2])

[[1.0 0.0 0.0 619 0 42 2 0.0 1 1 1 101348.88]
 [0.0 0.0 1.0 608 0 41 1 83807.86 1 0 1 112542.58]]


In [0]:
X=X[:, 1:] 

In [153]:
print(X[0:2])

[[0.0 0.0 619 0 42 2 0.0 1 1 1 101348.88]
 [0.0 1.0 608 0 41 1 83807.86 1 0 1 112542.58]]


In [0]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

### Feature Scaling

In [0]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train[:, [2,4,5,6,7,10]] = sc.fit_transform(X_train[:, [2,4,5,6,7,10]])
X_test[:, [2,4,5,6,7,10]] = sc.fit_transform(X_test[:, [2,4,5,6,7,10]])

In [156]:
X_train[0:2]

array([[0.0, 1.0, 0.16958176236487524, 0, -0.46460796076187094,
        0.006660987606337388, -1.215717487047255, 0.8095028981551377, 1,
        0, 1.1064316603959772],
       [1.0, 0.0, -2.304559451469164, 1, 0.3010255714048708,
        -1.3774403331910108, -0.006311925154929912, -0.9215912438499684,
        1, 1, -0.7486644675354392]], dtype=object)

In [0]:
X_train = X_train.astype('float64') 
X_test = X_test.astype('float64') 

### Splitting the dataset into the Training set and Test set

## Part 2 - Building the ANN

### Initializing the ANN

In [0]:
ann = tf.keras.models.Sequential()

### Adding the input layer and the first hidden layer

In [0]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

### Adding the second hidden layer

In [0]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

### Adding the output layer

In [0]:
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

## Part 3 - Training the ANN

### Compiling the ANN

In [0]:
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

### Training the ANN on the Training set

In [163]:
ann.fit(X_train, y_train, batch_size = 32, epochs = 100)

Epoch 1/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4995 - accuracy: 0.7806
Epoch 2/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4462 - accuracy: 0.8040
Epoch 3/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4302 - accuracy: 0.8074
Epoch 4/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4200 - accuracy: 0.8148
Epoch 5/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4118 - accuracy: 0.8198
Epoch 6/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4046 - accuracy: 0.8238
Epoch 7/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3978 - accuracy: 0.8285
Epoch 8/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3923 - accuracy: 0.8285
Epoch 9/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3870 - accuracy: 0.8304
Epoch 10/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3831 - accura

## Part 4 - Making the predictions and evaluating the model

### Predicting the Test set results

In [164]:
y_pred = ann.predict(X_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


### Making the Confusion Matrix

In [165]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)

[[1530   65]
 [ 215  190]]


In [167]:
(1530+190)/(2000)

0.86